discord:
  client_id: "1278694252985057303"
  client_secret: "pMa7Vx79zXKRNYRzW9MxtajKdRPBTEdO"
  token: "MTI3ODY5NDI1Mjk4NTA1NzMwMw.GAJXKV.Qpf3M9CFLFIKX04SNqtonDkhV4RbnT4s_9SFHY"

openai:
  api_key: "" # for ChatGPT integration (optional)

postgres:
  host: "localhost"
  port: 5432
  dbname: "embedg"
  user: "postgres"
  password: ""

app:
  public_url: "http://localhost:5173/app"

api:
  # Make sure to add {public_url}/auth/callback to the OAuth2 Redirect URLs of your application in the Discord dev portal
  public_url: "http://localhost:5173/api"

  # Make sure to enable this when you don't have an SSL (HTTPS) certificate
  insecure_cookies: true

  host: "localhost"
  port: 8080

# These links are used in help commands and for redirects
links:
  discord: https://discord.gg/CpHwbKQKHA
  source: https://github.com/merlinfuchs/embed-generator

log:
  use_json: false # Enable to this to have easily parsable JSON log messages (you usually don't want this)

# Here you can configure multiple tiers/plans which are linked to a Discord SKU
premium:
  plans:
    # The default plan that all users automatically have
    - id: default
      default: true
      features:
        max_saved_messages: 100
        max_actions_per_component: 10
        advanced_action_types: true
        ai_assistant: true
        is_premium: true
        custom_bot: true
        max_custom_commands: 25
        max_image_upload_size: 8000000
        max_scheduled_messages: 25
        periodic_scheduled_messages: true
        max_template_ops: 10000
        max_kv_keys: 1000
    # An additional premium plan that will apply when the user or guild has the SKU
    - id: premium_server
      sku_id: "123"
      features:
        max_saved_messages: 100
        max_actions_per_component: 10
        advanced_action_types: true
        ai_assistant: true
        is_premium: true # This is used for handing out cosmetics like a role on the support server
        custom_bot: true
        max_custom_commands: 25
        max_image_upload_size: 8000000
        max_scheduled_messages: 25
        periodic_scheduled_messages: true
        max_template_ops: 10000
        max_kv_keys: 1000
