name: Release Builds

on:
  release:
    types: [created]

jobs:
  release:
    name: Release Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Build Site
        run: npm install -g yarn && yarn install && yarn build
        working-directory: ./embedg-site
      - name: Build App
        run: npm install -g yarn && yarn install && yarn build
        working-directory: ./embedg-app
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          workdir: embedg-server
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
